name: thecellmap
channels:
- defaults
- conda-forge
dependencies:
- numpy
- scipy
- python=3.6
- Django<2
- psycopg2
- pandas
- openpyxl
- xlrd
- xlwt
- xlsxwriter
- beautifulsoup4
- scipy
- bcrypt
- notebook
- gsl
- uwsgi
- matplotlib
- cython
- nose
- python-memcached
- libiconv
- pip:
  - django-tables2
  - django-bootstrap-pagination
  - django-compressor
  - django-crispy-forms
  - django-require
  - django-nose
  - django-extensions
  - django-filter
  - django-htmlmin
  - sga-safe
  - intermine
