bind = '127.0.0.1:8000'
backlog = 2048

workers = 4
worker_class = 'egg:gunicorn#sync'
worker_connections = 1000
max_requests = 10
timeout = 600
keepalive = 2

debug = False
spew = False

accesslog = '/var/log/gunicorn/thecellmap-access.log'
errorlog = '/var/log/gunicorn/thecellmap-error.log'

user = 'thecellmap'
group = 'thecellmap'

