# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0006_gene_neighbor_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boonelab_id', models.TextField()),
                ('allele', models.TextField()),
                ('genotype', models.TextField()),
                ('gene1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains1', to='base.Gene')),
                ('gene2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strains2', to='base.Gene')),
            ],
        ),
    ]
