# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-26 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('pvalue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TriStrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boonelab_id', models.TextField()),
                ('allele', models.TextField()),
                ('genotype', models.TextField()),
                ('is_double_mutant', models.BooleanField()),
                ('is_query', models.BooleanField()),
                ('gene1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains1', to='base.Gene')),
                ('gene2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strains2', to='base.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='TriStrainSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('double_mutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_in_set', to='trigenic.TriStrain')),
                ('single_mutant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single1_in_set', to='trigenic.TriStrain')),
                ('single_mutant2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single2_in_set', to='trigenic.TriStrain')),
            ],
        ),
        migrations.AddField(
            model_name='triscores',
            name='array',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='array_scores', to='trigenic.TriStrain'),
        ),
        migrations.AddField(
            model_name='triscores',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_scores', to='trigenic.TriStrain'),
        ),
    ]
