# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-08 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trigenic', '0002_triscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triscores',
            name='array',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='array_scores', to='trigenic.TriStrain'),
        ),
        migrations.AlterField(
            model_name='triscores',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_scores', to='trigenic.TriStrain'),
        ),
    ]
