# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trigenic', '0003_auto_20170508_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriStrainSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tristrain',
            name='is_double_mutant',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tristrain',
            name='is_query',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tristrainset',
            name='double_mutant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='double_in_set', to='trigenic.TriStrain'),
        ),
        migrations.AddField(
            model_name='tristrainset',
            name='single_mutant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single1_in_set', to='trigenic.TriStrain'),
        ),
        migrations.AddField(
            model_name='tristrainset',
            name='single_mutant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single2_in_set', to='trigenic.TriStrain'),
        ),
    ]
