# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 15:53
from __future__ import unicode_literals

import dbarray.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=40, unique=True)),
                ('private', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('permanent', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(b'I', b'Interaction'), (b'C', b'Correlation')], default=b'C', max_length=1)),
                ('network_type', models.CharField(choices=[(b'U', b'Undirected'), (b'D', b'Directed')], default=b'U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('verbose_name', models.CharField(max_length=64)),
                ('public_description', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_sgdid', models.CharField(db_index=True, help_text=b'Primary SGDID', max_length=10, unique=True)),
                ('feature_qualifier', models.CharField(help_text=b'Feature qualifier', max_length=32)),
                ('orf', models.CharField(db_index=True, help_text=b'Feature name', max_length=16, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text=b'Standard gene name', max_length=16, null=True, unique=True)),
                ('aliases', dbarray.fields.CharArrayField(blank=True, help_text=b'Alias', max_length=152, null=True)),
                ('secondary_sgdid', dbarray.fields.CharArrayField(blank=True, help_text=b'Secondary SGDID', max_length=10, null=True)),
                ('chromosome', models.SmallIntegerField(help_text=b'Chromosome')),
                ('start', models.IntegerField(help_text=b'Start coordinate')),
                ('stop', models.IntegerField(help_text=b'Stop coordinate')),
                ('sorting_value', models.IntegerField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('sorting_value',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(max_length=64, null=True)),
                ('color', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='RegionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('alias', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allele', models.CharField(blank=True, max_length=24, null=True)),
                ('boonelab_id', models.CharField(help_text=b'Boonelab strain id, ex: tsq123', max_length=24)),
                ('genotype', models.CharField(max_length=512)),
                ('mating_type', models.CharField(max_length=8)),
                ('description', models.TextField(blank=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='StrainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'Q', b'Query'), (b'A', b'Array')], default=b'Q', max_length=1)),
                ('scores', dbarray.fields.FloatArrayField()),
                ('pvalues', dbarray.fields.FloatArrayField()),
                ('correlations', dbarray.fields.FloatArrayField(null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='base.Dataset')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Strain')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('alias', models.CharField(max_length=128)),
                ('source', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=6)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Annotation')),
                ('genes', models.ManyToManyField(to='base.Gene')),
            ],
        ),
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.SmallIntegerField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Region')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Strain')),
            ],
            options={
                'ordering': ('region', 'degree'),
            },
        ),
        migrations.AddField(
            model_name='region',
            name='region_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='base.RegionGroup'),
        ),
        migrations.AddField(
            model_name='region',
            name='vertices',
            field=models.ManyToManyField(through='base.Vertex', to='base.Strain'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='arrays',
            field=models.ManyToManyField(related_name='as_array', to='base.Strain'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='correlation_axis',
            field=models.ManyToManyField(related_name='as_correlation', to='base.Strain'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='queries',
            field=models.ManyToManyField(related_name='as_query', to='base.Strain'),
        ),
        migrations.AddField(
            model_name='custom',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customs', to='base.Dataset'),
        ),
        migrations.AddField(
            model_name='custom',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='vertex',
            unique_together=set([('region', 'degree'), ('region', 'strain')]),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set([('annotation', 'name', 'source')]),
        ),
        migrations.AlterUniqueTogether(
            name='custom',
            unique_together=set([('name', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together=set([('name', 'date')]),
        ),
    ]
