# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='strains',
            field=models.ManyToManyField(to='base.Strain'),
        ),
    ]
