# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20161028_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='r',
        ),
        migrations.RemoveField(
            model_name='region',
            name='x',
        ),
        migrations.RemoveField(
            model_name='region',
            name='y',
        ),
        migrations.AddField(
            model_name='region',
            name='label_align',
            field=models.CharField(blank=True, help_text=b'Alignment of this label', max_length=12),
        ),
        migrations.AddField(
            model_name='region',
            name='label_anchor',
            field=models.IntegerField(blank=True, help_text=b"Strain id to use as an anchor for this regions' label", null=True),
        ),
    ]
