# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_gene_neighbor_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='version',
            field=models.CharField(choices=[(b'G', b'Using Genes'), (b'S', b'Using Strains')], default=b'S', max_length=1),
        ),
    ]
