# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-08 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='version',
            field=models.CharField(choices=[('G', 'Using Genes'), ('S', 'Using Strains')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='custom',
            name='network_type',
            field=models.CharField(choices=[('U', 'Undirected'), ('D', 'Directed')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='custom',
            name='type',
            field=models.CharField(choices=[('I', 'Interaction'), ('C', 'Correlation')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='gene',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=152), blank=True, help_text='Alias', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gene',
            name='chromosome',
            field=models.SmallIntegerField(help_text='Chromosome'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='feature_qualifier',
            field=models.CharField(help_text='Feature qualifier', max_length=32),
        ),
        migrations.AlterField(
            model_name='gene',
            name='name',
            field=models.CharField(blank=True, db_index=True, help_text='Standard gene name', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='orf',
            field=models.CharField(db_index=True, help_text='Feature name', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='primary_sgdid',
            field=models.CharField(db_index=True, help_text='Primary SGDID', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='secondary_sgdid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, help_text='Secondary SGDID', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='gene',
            name='start',
            field=models.IntegerField(help_text='Start coordinate'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='stop',
            field=models.IntegerField(help_text='Stop coordinate'),
        ),
        migrations.AlterField(
            model_name='region',
            name='label_align',
            field=models.CharField(blank=True, help_text='Alignment of this label', max_length=12),
        ),
        migrations.AlterField(
            model_name='region',
            name='label_anchor',
            field=models.IntegerField(blank=True, help_text="Strain id to use as an anchor for this regions' label", null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='boonelab_id',
            field=models.CharField(help_text='Boonelab strain id, ex: tsq123', max_length=24),
        ),
        migrations.AlterField(
            model_name='straindata',
            name='type',
            field=models.CharField(choices=[('Q', 'Query'), ('A', 'Array')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
