# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_dataset_default_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='r',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
