# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-24 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161103_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='neighbor_effect',
            field=models.BooleanField(default=False),
        ),
    ]
